from .base import BaseFormatter
from typing import List, Tuple
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

class DocxFormatter(BaseFormatter):
    def format(self, results: List[Tuple['SourceFile', 'ExecutionResult']], config) -> str:
        # NOTE: This method signature implies returning a string (like markdown),
        # but python-docx works with objects.
        # We will generate the object, save it to a temp path or return bytes?
        # Protocol change: formatters should might need to handle file writing or return bytes.
        # For compatibility with BaseFormatter which returns str, we might need to adjust the interface
        # or have this return a dummy string and write to file internally (not ideal)
        # Re-evaluating: The CLI expects a string to write to file.
        # Better approach: Update BaseFormatter to `save(results, config, output_path)`?
        # For now, let's implement a save method and have format return a success message or path.
        pass

    def save(self, results: List[Tuple['SourceFile', 'ExecutionResult']], config, output_path: str):
        document = Document()
        
        # Styles
        style = document.styles['Normal']
        font = style.font
        font.name = 'Calibri'
        font.size = Pt(11)

        # 1. Header
        head = document.add_heading(config.project_title, 0)
        head.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        p = document.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        runner = p.add_run(f"Author: {config.author}\n")
        runner.bold = True
        p.add_run(f"Date: {datetime.now().strftime('%d %B %Y')}\n")
        p.add_run("Generated by CodeSubmit")
        
        document.add_page_break()

        # 2. Per File
        for file, result in results:
            # File Info
            h = document.add_heading(f"File: {file.rel_path}", level=1)
            
            p_meta = document.add_paragraph()
            p_meta.add_run(f"Language: {file.language}\n").bold = True
            p_meta.add_run(f"SHA256: {file.hash_digest}")
            
            # Code
            document.add_heading("Source Code", level=2)
            self._add_code_block(document, file.content)
            
            # Execution
            if result:
                 document.add_heading("Execution Output", level=2)
                 if result.timed_out:
                     p_warn = document.add_paragraph("WARNING: Execution Timed Out")
                     p_warn.style = 'Quote' 
                 
                 p_exec = document.add_paragraph()
                 p_exec.add_run(f"Command: {result.command}\n")
                 p_exec.add_run(f"Exit Code: {result.exit_code}\n")
                 p_exec.add_run(f"Duration: {result.duration:.3f}s")

                 if result.stdout.strip():
                     document.add_heading("Standard Output", level=3)
                     self._add_code_block(document, result.stdout)
                 
                 if result.stderr.strip():
                     document.add_heading("Standard Error", level=3)
                     self._add_code_block(document, result.stderr)

            document.add_page_break()
            
        # 3. Integrity Manifest
        document.add_heading("Integrity Manifest", level=1)
        table = document.add_table(rows=1, cols=2)
        table.style = 'Table Grid'
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'File'
        hdr_cells[1].text = 'SHA256 Hash'
        
        for file, _ in results:
            row_cells = table.add_row().cells
            row_cells[0].text = file.rel_path
            row_cells[1].text = file.hash_digest
            
        document.save(output_path)
        return "Saved"

    def _add_code_block(self, document, text):
        """Adds a paragraph mimicking a code block."""
        # This is basic. For real syntax highlighting we'd need rich text runs.
        # For now, just Courier New + shading?
        p = document.add_paragraph()
        run = p.add_run(text)
        run.font.name = 'Courier New'
        run.font.size = Pt(9)
        # TODO: Add shading/background if possible, or just strict formatting
