from .base import BaseFormatter
from typing import List, Tuple, Any
from datetime import datetime

class MarkdownFormatter(BaseFormatter):
    def format(self, results: List[Tuple['SourceFile', 'ExecutionResult']], config) -> str:
        # 'results' contains (SourceFile, ExecutionResult or None)
        
        output = []
        
        # 1. Document Header
        output.append(f"# {config.project_title}\n")
        output.append("## Metadata\n")
        output.append(f"* **Author:** {config.author}\n")
        output.append(f"* **Date:** {datetime.now().strftime('%d %B %Y')}\n")
        output.append(f"* **Generated By:** CodeSubmit\n")
        output.append("---\n\n")

        # 2. Per-File Section
        for file, result in results:
            output.append(f"## File: `{file.rel_path}`\n")
            output.append(f"* **Language:** {file.language}\n")
            output.append(f"* **SHA256:** `{file.hash_digest}`\n")
            
            output.append("\n### Source Code\n")
            # Use 4-tick fences for robustness if code contains 3-ticks, or just standard 3
            output.append(f"```{file.language.lower()}\n")
            output.append(file.content)
            output.append("\n```\n")
            
            if result:
                output.append("\n### Execution Output\n")
                if result.timed_out:
                    output.append("> [!WARNING]\n> **Execution Timed Out**\n\n")
                
                output.append(f"**Command:** `{result.command}`\n")
                output.append(f"**Exit Code:** {result.exit_code}\n")
                output.append(f"**Duration:** {result.duration:.3f}s\n")
                
                if result.stdout.strip():
                    output.append("\n**Standard Output:**\n")
                    output.append(f"```text\n{result.stdout}\n```\n")
                else:
                    output.append("\n*No Standard Output*\n")
                    
                if result.stderr.strip():
                    output.append("\n**Standard Error:**\n")
                    output.append(f"```text\n{result.stderr}\n```\n")
            else:
                if config.execution_enabled:
                     output.append("\n> [!NOTE]\n> Execution skipped (no runner or disabled).\n")
            
            output.append("\n---\n")
            
        # 3. Integrity Manifest
        output.append("\n## Integrity Manifest\n")
        output.append("| File | SHA256 Hash |\n")
        output.append("| :--- | :--- |\n")
        for file, _ in results:
            output.append(f"| `{file.rel_path}` | `{file.hash_digest}` |\n")
            
        return "".join(output)

