from .base import BaseFormatter
from typing import List, Tuple
import io

try:
    from xhtml2pdf import pisa
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

class PdfFormatter(BaseFormatter):
    def format(self, results: List[Tuple['SourceFile', 'ExecutionResult']], config) -> str:
        return ""

    def save(self, results: List[Tuple['SourceFile', 'ExecutionResult']], config, output_path: str):
        if not PDF_AVAILABLE:
             raise ImportError("PDF export requires 'xhtml2pdf'. Install it with: pip install xhtml2pdf")

        html_content = []
        html_content.append("""
        <html>
        <head>
            <style>
                @page { size: A4; margin: 2cm; @frame footer { -pdf-frame-content: footerContent; bottom: 1cm; margin-left: 2cm; margin-right: 2cm; height: 1cm; } }
                body { font-family: Helvetica, sans-serif; font-size: 10pt; }
                h1 { text-align: center; color: #2c3e50; font-size: 24pt; padding-bottom: 20px; }
                h2 { color: #2c3e50; border-bottom: 1px solid #ccc; padding-top: 10px; margin-top: 20px; font-size: 16pt; }
                p { margin-bottom: 5px; }
                .metadata { text-align: center; margin-bottom: 30px; font-size: 12pt; }
                .file-info { background-color: #f0f0f0; padding: 5px; border-left: 5px solid #333; margin-bottom: 10px; }
                pre { background-color: #f5f5f5; border: 1px solid #ccc; padding: 10px; font-family: "Courier New", monospace; font-size: 8pt; white-space: pre-wrap; word-wrap: break-word; }
                .execution-block { margin-top: 10px; border: 1px dashed #999; padding: 10px; }
                .success { color: green; }
                .failure { color: red; }
                .page-break { pdf-break-before: always; }
                table { width: 100%; border: 1px solid #ccc; }
                th { background-color: #eee; text-align: left; padding: 5px; }
                td { padding: 5px; border-top: 1px solid #ddd; }
            </style>
        </head>
        <body>
        """)
        
        # Header
        html_content.append(f"<h1>{config.project_title}</h1>")
        html_content.append(f"<div class='metadata'><p><strong>Author:</strong> {config.author}</p><p>Generated by CodeSubmit</p></div>")
        
        # Files
        for file, result in results:
            html_content.append("<div class='page-break'></div>")
            html_content.append(f"<h2>File: {file.rel_path}</h2>")
            html_content.append(f"<div class='file-info'><p><strong>Language:</strong> {file.language} &nbsp;|&nbsp; <strong>SHA256:</strong> {file.hash_digest[:16]}...</p></div>")
            
            html_content.append("<h3>Source Code</h3>")
            # Escape HTML in content
            safe_content = file.content.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            html_content.append(f"<pre>{safe_content}</pre>")
            
            if result:
                html_content.append("<div class='execution-block'>")
                html_content.append("<h3>Execution Output</h3>")
                
                status_class = "failure" if result.exit_code != 0 or result.timed_out else "success"
                status_text = "PASSED" if status_class == "success" else "FAILED"
                if result.timed_out: status_text = "TIMED OUT"
                
                html_content.append(f"<p><strong class='{status_class}'>Status: {status_text}</strong></p>")
                html_content.append(f"<p>Command: <code>{result.command}</code></p>")
                html_content.append(f"<p>Runtime: {result.duration:.3f}s</p>")
                
                if result.stdout.strip():
                     safe_out = result.stdout.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                     html_content.append(f"<h4>Stdout</h4><pre>{safe_out}</pre>")
                if result.stderr.strip():
                     safe_err = result.stderr.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                     html_content.append(f"<h4>Stderr</h4><pre>{safe_err}</pre>")
                html_content.append("</div>")

        # Manifest
        html_content.append("<div class='page-break'></div>")
        html_content.append("<h2>Integrity Manifest</h2>")
        html_content.append("<table><tr><th>File</th><th>SHA256 Hash</th></tr>")
        for file, _ in results:
            html_content.append(f"<tr><td>{file.rel_path}</td><td>{file.hash_digest}</td></tr>")
        html_content.append("</table>")
        
        # Footer Frame content
        html_content.append("""
        <div id="footerContent">
            Page <pdf:pagenumber />
        </div>
        </body></html>
        """)
        
        full_html = "".join(html_content)
        
        with open(output_path, "wb") as pdf_file:
            pisa_status = pisa.CreatePDF(io.StringIO(full_html), dest=pdf_file)
            
        if pisa_status.err:
             raise RuntimeError(f"PDF generation failed: {pisa_status.err}")

